Ext.apply(Ext.ux.UploadDialog.Dialog.prototype.i18n, {
	title : '导入文件',
	state_col_title : '状态',
	state_col_width : 70,
	filename_col_title : '文件名',
	filename_col_width : 230,
	note_col_title : '结果信息',
	note_col_width : 150,
	add_btn_text : '选择',
	add_btn_tip : '选择一个文件加入到导入文件的列表中',
	remove_btn_text : '删除',
	remove_btn_tip : '导入文件的列表中删除选中的文件',
	reset_btn_text : '重置',
	reset_btn_tip : '导入文件的列表重置',
	upload_btn_start_text : '导入',
	upload_btn_stop_text : '停止',
	upload_btn_start_tip : '将导入文件的列表中的文件逐条导入到系统中',
	upload_btn_stop_tip : '停止导入',
	close_btn_text : '关闭',
	close_btn_tip : '关闭导入窗口',
	progress_waiting_text : '等待中...',
	progress_uploading_text : '导入中: 第{0}个文件已完成，总数 {1}个文件需导入',
	error_msgbox_title : '错误',
	permitted_extensions_join_str : ',',
	err_file_type_not_permitted : '该文件格式不支持<br/>请选择支持格式的文件: {1}',
	note_queued_to_upload : '等待导入的文件',
	note_processing : '导入中...',
	note_upload_failed : '服务器发生异常',
	note_upload_success : '成功',
	note_upload_error : '导入失败',
	note_aborted : '已被用户停止',
	note_canceled : '导入被取消',
	err_file_name_exits : '该文件已存在'
});